version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A tasks.app worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A tasks.app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - celery_worker
